# Generated by Django 3.1.6 on 2021-02-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0002_auto_20210210_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
