# Generated by Django 3.1.6 on 2021-02-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0003_user_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
