# Generated by Django 3.1.6 on 2021-02-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contestchips',
            new_name='Contestchip',
        ),
    ]
