# Generated by Django 3.1.6 on 2021-02-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210211_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(choices=[('P', 'Single option correct'), ('C', 'Multiple options correct'), ('X', 'Integer type question')], max_length=20),
        ),
    ]
