# Generated by Django 3.1.6 on 2021-02-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210211_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='integer_content',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='options',
            field=models.ManyToManyField(null=True, to='core.Option'),
        ),
    ]
