# Generated by Django 3.1.6 on 2021-02-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadrant', '0002_quadcontestapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadcontestapplication',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
