# Generated by Django 3.1.6 on 2021-02-12 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210212_0416'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quadrant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuadContestApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadapplications', to='core.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadapplications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
