# Generated by Django 3.1.6 on 2021-02-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210210_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='content_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
