# Generated by Django 3.1.6 on 2021-02-10 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0005_watchfriend'),
        ('core', '0003_auto_20210210_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestprocess',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appauth.rating'),
        ),
    ]
