# Generated by Django 3.1.6 on 2021-02-10 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0005_watchfriend'),
        ('core', '0004_contestprocess_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestprocess',
            name='rated_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contestprocess',
            name='rating_change',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ch_processes', to='appauth.rating'),
        ),
        migrations.AlterField(
            model_name='contestprocess',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='appauth.rating'),
        ),
    ]
