# Generated by Django 3.1.6 on 2021-02-10 16:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210210_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('score_all', models.IntegerField(null=True)),
                ('score_m', models.IntegerField(null=True)),
                ('score_p', models.IntegerField(null=True)),
                ('score_c', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='contestprocess',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.score'),
        ),
    ]
