# Generated by Django 3.1.6 on 2021-02-10 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_submission_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='problm_type',
            new_name='problem_type',
        ),
        migrations.AddField(
            model_name='problem',
            name='contest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='core.contest'),
            preserve_default=False,
        ),
    ]
