# Generated by Django 3.1.6 on 2021-02-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210211_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
