# Generated by Django 3.1.6 on 2021-02-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210211_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
