# Generated by Django 3.1.6 on 2021-02-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210211_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contest_status',
            field=models.CharField(choices=[('P', 'Proposed'), ('A', 'Accepted'), ('D', 'Over')], default='P', max_length=10),
        ),
    ]
