# Generated by Django 3.1.6 on 2021-02-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_contest_contest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(choices=[('S', 'Single option correct'), ('M', 'Multiple options correct'), ('I', 'Integer type question')], max_length=20),
        ),
    ]
