# Generated by Django 3.1.6 on 2021-02-12 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210212_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='contestprocess',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.contestprocess'),
        ),
    ]
