# Generated by Django 3.1.6 on 2021-02-14 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210212_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='writer',
        ),
    ]
