# Generated by Django 3.1.6 on 2021-02-14 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_remove_problem_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='writers',
        ),
        migrations.AddField(
            model_name='problem',
            name='writer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='written_problems', to='appauth.user'),
            preserve_default=False,
        ),
    ]
