# Generated by Django 3.1.6 on 2022-05-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210307_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='test_data',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='training_data',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='pickle_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(choices=[('S', 'Single option correct'), ('M', 'Multiple options correct'), ('I', 'Integer type question'), ('P', 'Pickle File Upload')], max_length=20),
        ),
    ]
